### ISSUE TITLE
spotipy is missing in "install_requires"

### ISSUE THREAD

**Issue by guettli** [yash2696/BeautifyMP3#3]
```
(audio-rename) guettli@yoga15:~/projects/audio-rename/BeautifyMP3$ python addMetadata.py 
Traceback (most recent call last):
  File "addMetadata.py", line 24, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'


(audio-rename) guettli@yoga15:~/projects/audio-rename/BeautifyMP3$ pip install spotipy
Collecting spotipy
  Downloading spotipy-2.19.0-py3-none-any.whl (27 kB)
Collecting urllib3>=1.26.0
  Downloading urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB 3.0 MB/s            
Collecting requests>=2.25.0
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting six>=1.15.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 2.6 MB/s            
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.7-py3-none-any.whl (38 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
     |████████████████████████████████| 149 kB 1.4 MB/s            
Installing collected packages: urllib3, idna, charset-normalizer, certifi, six, requests, spotipy
Successfully installed certifi-2021.10.8 charset-normalizer-2.0.7 idna-3.3 requests-2.26.0 six-1.16.0 spotipy-2.19.0 urllib3-1.26.7
```

But now:

```
(audio-rename) guettli@yoga15:~/projects/audio-rename/BeautifyMP3$ python addMetadata.py 
Traceback (most recent call last):
  File "addMetadata.py", line 29, in <module>
    from titlecase import titlecase
ModuleNotFoundError: No module named 'titlecase'
```

... giving up.

**Comment by JetStyle51** [comment]
Same issue...
